// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/device-management-toolkit/go-wsman-messages/v2/pkg/security (interfaces: Cryptor)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/cryptor_mocks.go -package=mocks github.com/device-management-toolkit/go-wsman-messages/v2/pkg/security Cryptor
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	config "github.com/device-management-toolkit/go-wsman-messages/v2/pkg/config"
	gomock "go.uber.org/mock/gomock"
)

// MockCryptor is a mock of Cryptor interface.
type MockCryptor struct {
	ctrl     *gomock.Controller
	recorder *MockCryptorMockRecorder
	isgomock struct{}
}

// MockCryptorMockRecorder is the mock recorder for MockCryptor.
type MockCryptorMockRecorder struct {
	mock *MockCryptor
}

// NewMockCryptor creates a new mock instance.
func NewMockCryptor(ctrl *gomock.Controller) *MockCryptor {
	mock := &MockCryptor{ctrl: ctrl}
	mock.recorder = &MockCryptorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCryptor) EXPECT() *MockCryptorMockRecorder {
	return m.recorder
}

// Decrypt mocks base method.
func (m *MockCryptor) Decrypt(cipherText string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decrypt", cipherText)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Decrypt indicates an expected call of Decrypt.
func (mr *MockCryptorMockRecorder) Decrypt(cipherText any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decrypt", reflect.TypeOf((*MockCryptor)(nil).Decrypt), cipherText)
}

// Encrypt mocks base method.
func (m *MockCryptor) Encrypt(plainText string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Encrypt", plainText)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Encrypt indicates an expected call of Encrypt.
func (mr *MockCryptorMockRecorder) Encrypt(plainText any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Encrypt", reflect.TypeOf((*MockCryptor)(nil).Encrypt), plainText)
}

// EncryptWithKey mocks base method.
func (m *MockCryptor) EncryptWithKey(plainText, key string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EncryptWithKey", plainText, key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EncryptWithKey indicates an expected call of EncryptWithKey.
func (mr *MockCryptorMockRecorder) EncryptWithKey(plainText, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EncryptWithKey", reflect.TypeOf((*MockCryptor)(nil).EncryptWithKey), plainText, key)
}

// GenerateKey mocks base method.
func (m *MockCryptor) GenerateKey() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateKey")
	ret0, _ := ret[0].(string)
	return ret0
}

// GenerateKey indicates an expected call of GenerateKey.
func (mr *MockCryptorMockRecorder) GenerateKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateKey", reflect.TypeOf((*MockCryptor)(nil).GenerateKey))
}

// ReadAndDecryptFile mocks base method.
func (m *MockCryptor) ReadAndDecryptFile(filePath string) (config.Configuration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadAndDecryptFile", filePath)
	ret0, _ := ret[0].(config.Configuration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadAndDecryptFile indicates an expected call of ReadAndDecryptFile.
func (mr *MockCryptorMockRecorder) ReadAndDecryptFile(filePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadAndDecryptFile", reflect.TypeOf((*MockCryptor)(nil).ReadAndDecryptFile), filePath)
}
