// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/controller/ws/v1/interface.go
//
// Generated by this command:
//
//	mockgen -source ./internal/controller/ws/v1/interface.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	http "net/http"
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	websocket "github.com/gorilla/websocket"
	gomock "go.uber.org/mock/gomock"
)

// MockUpgrader is a mock of Upgrader interface.
type MockUpgrader struct {
	ctrl     *gomock.Controller
	recorder *MockUpgraderMockRecorder
	isgomock struct{}
}

// MockUpgraderMockRecorder is the mock recorder for MockUpgrader.
type MockUpgraderMockRecorder struct {
	mock *MockUpgrader
}

// NewMockUpgrader creates a new mock instance.
func NewMockUpgrader(ctrl *gomock.Controller) *MockUpgrader {
	mock := &MockUpgrader{ctrl: ctrl}
	mock.recorder = &MockUpgraderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpgrader) EXPECT() *MockUpgraderMockRecorder {
	return m.recorder
}

// Upgrade mocks base method.
func (m *MockUpgrader) Upgrade(w http.ResponseWriter, r *http.Request, hdr http.Header) (*websocket.Conn, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upgrade", w, r, hdr)
	ret0, _ := ret[0].(*websocket.Conn)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upgrade indicates an expected call of Upgrade.
func (mr *MockUpgraderMockRecorder) Upgrade(w, r, hdr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upgrade", reflect.TypeOf((*MockUpgrader)(nil).Upgrade), w, r, hdr)
}

// MockRedirect is a mock of Redirect interface.
type MockRedirect struct {
	ctrl     *gomock.Controller
	recorder *MockRedirectMockRecorder
	isgomock struct{}
}

// MockRedirectMockRecorder is the mock recorder for MockRedirect.
type MockRedirectMockRecorder struct {
	mock *MockRedirect
}

// NewMockRedirect creates a new mock instance.
func NewMockRedirect(ctrl *gomock.Controller) *MockRedirect {
	mock := &MockRedirect{ctrl: ctrl}
	mock.recorder = &MockRedirectMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRedirect) EXPECT() *MockRedirectMockRecorder {
	return m.recorder
}

// Redirect mocks base method.
func (m *MockRedirect) Redirect(c *gin.Context, conn *websocket.Conn, host, mode string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Redirect", c, conn, host, mode)
	ret0, _ := ret[0].(error)
	return ret0
}

// Redirect indicates an expected call of Redirect.
func (mr *MockRedirectMockRecorder) Redirect(c, conn, host, mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Redirect", reflect.TypeOf((*MockRedirect)(nil).Redirect), c, conn, host, mode)
}
