version: "2"
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - cyclop
    - dogsled
    - durationcheck
    - err113
    - errcheck
    - errorlint
    - exhaustive
    - forbidigo
    - funlen
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gomodguard
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - makezero
    - misspell
    - mnd
    - nakedret
    - nestif
    - nlreturn
    - noctx
    - nolintlint
    - paralleltest
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - whitespace
    - wsl_v5
  settings:
    cyclop:
      max-complexity: 15
    errcheck:
      check-type-assertions: true
      check-blank: false
    errorlint:
      errorf: true
    exhaustive:
      default-signifies-exhaustive: false
    funlen:
      lines: 100
      statements: 45
    gocognit:
      min-complexity: 16
    goconst:
      min-len: 2
      min-occurrences: 2
    gocritic:
      disabled-checks:
        - dupImport
        - unnecessaryBlock
        - hugeParam
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 15
    misspell:
      locale: US
    mnd:
      checks:
        - argument
        - case
        - condition
        - operation
        - return
    nestif:
      min-complexity: 5
    nolintlint:
      require-explanation: true
      require-specific: true
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - godot
          - paralleltest
        path: integration-test
      - linters:
          - godot
        path: internal/controller/http
      - linters:
          - err113
          - funlen
        path: (.+)_test.go
    paths:
      - docs
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - Standard
        - Default
        - Prefix(github.com/device-management-toolkit)
        - localmodule
    gofumpt:
      extra-rules: true
  exclusions:
    generated: lax
    paths:
      - docs
      - third_party$
      - builtin$
      - examples$
