services:
  vault:
    image: hashicorp/vault
    networks:
      - dmtnetwork1
    ports:
      - '8200:8200'
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: myroot
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    cap_add:
      - IPC_LOCK
  postgres:
    container_name: postgres
    image: postgres
    networks:
      - dmtnetwork1
    volumes:
      - pg-data:/var/lib/postgresql
    environment:
      POSTGRES_USER: "postgresadmin"
      POSTGRES_PASSWORD: "admin123"
      POSTGRES_DB: "rpsdb"
    ports:
      - 5432:5432
  app:
    build: .
    container_name: app
    image: app
    networks:
      - dmtnetwork1
    env_file:
      - .env
    environment:
      APP_ENCRYPTION_KEY: "Jf3Q2nXJ+GZzN1dbVQms0wbB4+i/5PjL" # This is a test encryption key for the app
      HTTP_HOST: ""
      HTTP_TLS_ENABLED: "false"
      GIN_MODE: "debug"
      DB_URL: "postgres://postgresadmin:admin123@postgres:5432/rpsdb"
      AUTH_DISABLED: true
      CONSUL_ENABLED: ${CONSUL_ENABLED:-false}
      CONSUL_HOST: ${CONSUL_HOST:-consul}
      CONSUL_PORT: ${CONSUL_PORT:-8500}
      CONSUL_KEY_PREFIX: ${CONSUL_KEY_PREFIX:-console}
    ports:
      - 8181:8181
    depends_on:
      - postgres
  consul:
    restart: always
    image: hashicorp/consul
    networks:
      - dmtnetwork1
    ports:
      - 8500:8500
    profiles:
      - consul
    volumes:
      - type: volume
        source: consul-config
        target: /consul/config
        volume: {}
      - type: volume
        source: consul-data
        target: /consul/data
        volume: {}
    command: "agent -server -ui -node=OACT-1 -bootstrap-expect=1 -client=0.0.0.0"
  # integration:
  #   build:
  #     context: .
  #     dockerfile: integration-test/Dockerfile
  #   container_name: integration
  #   image: integration
  #   depends_on:
  #     - app
volumes:
  pg-data:
  consul-config:
  consul-data:
networks:
  dmtnetwork1:
    driver: "bridge"
