app:
  name: console
  repo: device-management-toolkit/console
  version: DEVELOPMENT
  encryption_key: ""
  allow_insecure_ciphers: false
http:
  host: localhost
  port: "8181"
  # set to true for WAN settings where bandwidth is a concern, false for LAN/low latency/high bandwidth
  ws_compression: false
  tls:
    enabled: true
    # If certFile/keyFile are both empty and enabled is true, a self-signed certificate will be generated at runtime.
    certFile: ""
    keyFile: ""
  allowed_origins:
    - "*"
  allowed_headers:
    - "*"
logger:
  log_level: info
postgres:
  pool_max: 2
  url: ""
ea:
  url: http://localhost:8000
  username: ""
  password: ""
auth:
  disabled: false
  adminUsername: standalone
  adminPassword: G@ppm0ym
  jwtKey: your_secret_jwt_key
  jwtExpiration: 24h0m0s
  redirectionJWTExpiration: 5m0s
  clientId: ""
  issuer: ""
  ui: 
    clientId: ""
    issuer: ""
    scope: ""
    redirectUri: ""
    responseType: "code"
    requireHttps: false
    strictDiscoveryDocumentValidation: true

