app:
  name: "console"
  repo: "open-amt-cloud-toolkit/console"
  jwtKey: "your_secret_jwt_key"
  adminUsername: "standalone"
  adminPassword: "G@ppm0ym"
http:
  host: "localhost"
  port: "8181"
  allowed_origins:
    - "*"
  allowed_headers:
    - "*"

logger:
  log_level: "debug"

postgres:
  pool_max: 5