name: Console API Tests


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4 # v2.7.1
      with:
        egress-policy: audit

    - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
    - run: cp .env.example .env
    - run: docker compose up -d --build
    
    - name: Let Docker Spin up
      run: sleep 5
    - name: Run Console API Tests
      run: docker run --network=host -v  /home/runner/work/console/console/integration-test/:/collections -v /home/runner/work/console/console/integration-test/results/:/results postman/newman:5.3-alpine run /collections/console.postman_collection.json -e /collections/console.postman_environment.json --insecure --reporters cli,json,junit --reporter-json-export /results/console_api_results.json --reporter-junit-export /results/console_api_results_junit.xml
    - name: Dump docker logs on failure
      if: failure()
      uses: jwalton/gh-docker-logs@v2
    - name: Upload Postman Results
      uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
      with:
        name: rps-api
        path: /home/runner/work/console/console/integration-test/results