name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
      branches: [ main ]
  workflow_dispatch:
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
      with:
        egress-policy: audit

    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.0.0
    - name: Build the Docker image
      run: docker build --file Dockerfile --tag  vprodemo.azurecr.io/console:latest --tag vprodemo.azurecr.io/console:${{ github.sha }} .
    - name: Docker Login
      if: ${{ github.ref == 'refs/heads/main' }}      
      uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
      with:
        registry: vprodemo.azurecr.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        logout: true
    - name: Push the Docker image to the registry
      if: ${{ github.ref == 'refs/heads/main' }}      
      run: docker push vprodemo.azurecr.io/console:latest
    - name: Push the Docker image to the registry
      if: ${{ github.ref == 'refs/heads/main' }}      
      run: docker push vprodemo.azurecr.io/console:${{ github.sha }}
