name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
      branches: [ main ]
  workflow_dispatch:
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
      with:
        egress-policy: audit

    - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.0.0
    - name: Build the Docker image
      run: docker build --file Dockerfile --tag  vprodemo.azurecr.io/console:latest --tag vprodemo.azurecr.io/console:${{ github.sha }} .
    - name: Docker Login
      if: ${{ github.ref == 'refs/heads/main' }}      
      uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20 # v3.1.0
      with:
        registry: vprodemo.azurecr.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        logout: true
    - name: Push the Docker image to the registry
      if: ${{ github.ref == 'refs/heads/main' }}      
      run: docker push vprodemo.azurecr.io/console:latest
    - name: Push the Docker image to the registry
      if: ${{ github.ref == 'refs/heads/main' }}      
      run: docker push vprodemo.azurecr.io/console:${{ github.sha }}
